export default [
    {
      "_id": "605fc76756b7e70015aec048",
      "name": "Cultos VXL",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(1).jpg?alt=media&token=8af32133-0e9e-467a-81d5-83d9922462da",
      "description": "Suzuki Cultus VXL comes in 7 different colors i.e Pearl Red, Graphite Grey, White, Silky Silver, Sand Beige, Super Pearl Black, Cerulean Blue.",
      "mark": "Susuki",
      "price": 12,
      "creationYear": 2016,
      "owner": "Raza Ali",
      "bussinessName": "Kwhawa rent a cart",
      "address": "Aiz address demostration",
      "stock": 10,
      "features": {
        "doors": 4,
        "capacity": 5,
        "typeTransmission": "Automatic",
        "typeCart": "Hatchback",
        "typeFuel": "Petrol",
        "cc": 1000,
        "year": 2021
      },
      "timeUsed": 0
    },
    {
      "_id": "605fc76756b7e70015aec049",
      "name": "Toyota Camry",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(2).png?alt=media&token=8a98c34f-a299-459d-a332-afd3c15ea75c",
      "description": "The Toyota Camry is a D-segment passenger car produced by the Japanese manufacturer Toyota. It is a five-seater vehicle, which was initially launched as a saloon version of the Toyota Celica sports car and that throughout its existence would change its appearance, until it was converted into a luxury car, as its last generations were offered.",
      "mark": "Toyota",
      "price": 10,
      "creationYear": 2016,
      "owner": "Rodrigo Afterment",
      "bussinessName": "Toyota Car",
      "address": "Pennsylvania - PA",
      "stock": 15,
      "features": {
        "doors": 4,
        "capacity": 5,
        "typeTransmission": "Mecanic",
        "typeCart": "Hatchback",
        "typeFuel": "Petrol",
        "cc": 1000,
        "year": 2020
      },
      "timeUsed": 0
    },
    {
      "_id": "605fc76756b7e70015aec04a",
      "name": "Onix 2021",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(3).png?alt=media&token=d573f468-f2b4-4dbf-af69-850b4f5a91c1",
      "description": "The all-new Chevrolet Onix challenges the status quo in its segment with never-before-seen features that make it an unforgettable first impression.",
      "mark": "Chevrolet",
      "price": 13,
      "creationYear": 2021,
      "owner": "Clontend Ali",
      "bussinessName": "Chevrolet Onix",
      "address": "Texas - TX",
      "stock": 13,
      "features": {
        "doors": 4,
        "capacity": 5,
        "typeTransmission": "Automatic",
        "typeCart": "Sedan",
        "typeFuel": "GNV",
        "cc": 1200,
        "year": 2020
      },
      "timeUsed": 0
    },
    {
      "_id": "605fc76756b7e70015aec04b",
      "name": "Cavalier",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(4).png?alt=media&token=15e93ed8-4708-49cc-a8fe-ddf1509f13a7",
      "description": "More than a car, it is the reflection of a way of life. It draws everyone\"s attention to every kilometer traveled.Halogen headlights with projector. LED taillights. Electric sunroof. Electric and heated side mirrors. Newly designed 16 ”aluminum wheels.",
      "mark": "Chevrolet",
      "price": 16,
      "creationYear": 2018,
      "owner": "Amanda T Gabriel",
      "bussinessName": "Chevrolet Cavalier",
      "address": "Wisconsin - Wausau",
      "stock": 20,
      "features": {
        "doors": 4,
        "capacity": 5,
        "typeTransmission": "Automatic",
        "typeCart": "Sedan",
        "typeFuel": "Gas",
        "cc": 1200,
        "year": 2021
      },
      "timeUsed": 0
    },
    {
      "_id": "605fc76756b7e70015aec04c",
      "name": "Chevy Blazer 2021",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(5).png?alt=media&token=32b3d967-4aa2-445f-a55e-4bf0491326ae",
      "description": "With a sophisticated bold design and performance and capability to match, the Blazer has a blend of style and substance for a totally extraordinary experience every time you drive.",
      "mark": "Chevrolet",
      "price": 20,
      "creationYear": 2021,
      "owner": "Elizabeth A Terry",
      "bussinessName": "Chevrolet Chevy Blazer",
      "address": "Indiana - 2257 Henery Street",
      "stock": 5,
      "features": {
        "doors": 5,
        "capacity": 6,
        "typeTransmission": "Mecanic",
        "typeCart": "SUV",
        "typeFuel": "Gas",
        "cc": 1800,
        "year": 2021
      },
      "timeUsed": 0
    },
    {
      "_id": "605fc76756b7e70015aec04d",
      "name": "Foton Tunland S 2017",
      "image": "https://firebasestorage.googleapis.com/v0/b/rentcarts.appspot.com/o/carts%2F1%20(6).png?alt=media&token=490f995d-3a0d-4a57-8a43-f8dbdcf277aa",
      "description": "It comes with a new high-tech powertrain, Cummins powertrain, a Getrag gearbox, German technology; a BorgWarner transfer case, American technology; a DANA differential rear axle; (also) American technology, and a Bosch Common Rail injection system ”",
      "mark": "Tunland",
      "price": 20,
      "creationYear": 2017,
      "owner": "Paul E Joseph",
      "bussinessName": "Foton Tunland S",
      "address": "South Dakota - 3197  Friendship Lane",
      "stock": 7,
      "features": {
        "doors": 4,
        "capacity": 6,
        "typeTransmission": "Mecanic",
        "typeCart": "Pickup",
        "typeFuel": "Petrol",
        "cc": 2500,
        "year": 2021
      },
      "timeUsed": 0
    }
]